---
title: "saving_data"
author: "Abbie Weight"
format: html
editor: visual
---

## Saving data

```{r}
#save to disk
iris
#write table function: x is object to write, file = what you want to call it, sep = separate by (delimiter for your file, tab would be "\t")
write.table(x = iris, file = "iris_copy.csv", sep = ",")

#to write text lines to a connection, make notes/a text file:
writeLines("this is my text output", con = "write-lines-example")

#to save the object as is, compressed in memory on your disk: good for saving large files
saveRDS(object = iris, file = "iris_dataframe.rds")

#to pull back from disk: need to save as a variable
iris_from_disk <- readRDS(file = "iris_dataframe.rds")
```

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)

deaths <- VADeaths |>
  as_tibble(rownames = "age_range") |>
  pivot_longer(cols = -age_range,
               names_to = "group",
               values_to = "mean_deaths")

ggplot(deaths, aes(x=group, y = age_range)) +
  geom_tile(aes(fill=mean_deaths))
  




```

```{r}

```
